sudo: required
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
before_install:
  - sudo ln -sf /usr/bin/gcc /usr/bin/gcc-4.7
install: make release
